### ISSUE TITLE
torch-mesh-isect is not compatible with your environment.yml

### ISSUE THREAD

**Issue by VisionaryMind** [MoyGcc/hpcwild#1]
Thank you for publishing this code. It is quite intriguing! Unfortunately, torch-mesh-isect does not work with the environment.yml you have published. I presume it because of an incompatibility with CUDA versions greater than 9. I am unable to compile and install it with CUDA 10.2, and it would appear to be an issue for all [v10 installations](https://github.com/vchoutas/torch-mesh-isect/issues/28).

Is it possible to eliminate or workaround the torch-mesh-isect dependency? Perhaps use a similar (but more up-to-date) library?

**Comment by MoyGcc** [comment]
Hi, thank you for your kind words! I also encountered problems while I tried to install torch-mesh-isect for the first time (CUDA 10.2). And I found almost all of the solutions in https://github.com/vchoutas/torch-mesh-isect/issues/23. Hope that could help you with the installation. And I can see there are also users have successfully made it run with quite new CUDA version https://github.com/vchoutas/torch-mesh-isect/issues/27. So I guess it would not be a big problem.

In this project, we use torch-mesh-isect as a part of post-processing to remove artifacts produced during registration to SMPL with offsets. You can simply work around this library by skipping the smoothing step in the post-processing https://github.com/MoyGcc/hpcwild/blob/main/registration/smoothing.py. As a trade-off, you might need to increase the weight for Laplacian loss to avoid possible non-smoothness of the surface which will lead to a bit less-detailed result.https://github.com/MoyGcc/hpcwild/blob/dea76d731cf108e77e1e3625fc42a1f444874569/registration/smpl_registration/fit_SMPLD.py#L47 

Feel free to ask follow-up questions if you meet other issues.

**Comment by VisionaryMind** [comment]
Thank you for the prompt response. I was eventually able to get torch-mesh-isect installed by downgrading Conda cudatoolkit to 10.0. Looking at that code's README, they state it had only been tested up to 10.0. Perhaps it could be forced to work with Cuda 11+, but at least for now, I have a way forward.

**Comment by MoyGcc** [comment]
Cool! I will close this issue.
