### ISSUE TITLE
Multiple changes to dependencies and code required

### ISSUE THREAD

**Issue by VisionaryMind** [MoyGcc/hpcwild#2]
I have been able to get your project working on my end, but I ran into several obstacles along the way and wanted to share the modifications required to make installation more generic. Here are the steps I took:

1. Create a `test_images` directory at project ROOT (it was missing).
2. Include additional PIP dependencies: `pyhocon, ipykernel, pycocotools, chumpy, smplpytorch`
3. Install PyMCubes with `pip install git+https://github.com/pmneila/PyMCubes.git`
4. Git clone NuScenes-Devkit from `https://github.com/nutonomy/nuscenes-devkit.git` and install from setup directory.
5. Manually install PyTorch3d with `pip install git+https://github.com/facebookresearch/pytorch3d.git@v0.6.1`

6. Further, there are several places the code needs to change, because it is pointing to your personal home directory (/home/chen). Here are the locations:

**registration/lib**
th_SMPL.py
```
smpl_right_hand_idx = np.load('assets/smpl_right_hand_idx.npy')
smpl_left_hand_idx = np.load('assets/smpl_left_hand_idx.npy')
```
smpl_layer.py
```
self.model_path = 'smpl_rendering/smpl_model/SMPL_FEMALE.pkl'
self.model_path = 'smpl_rendering/smpl_model/SMPL_MALE.pkl'	
```
smpl_paths.py
`fname = 'registration/faces.npy'`

**registration/smpl_registration**
fit_SMPLD_final.py
`part_labels = pkl.load(open('assets/smpl_parts_dense.pkl', 'rb'))`

**smpl_rendering**
smpl_renderer.py
` _, faces, aux = load_obj('smpl_rendering/text_uv_coor_smpl.obj', load_textures=True)`

7. Next, the smpl_parts_dense.pkl file is missing from [IPNet](https://github.com/bharat-b7/IPNet), so those assets needed to be copied over as well.

With these changes, the entire pipeline works. The only question I have for you is how you have generated the sequence in your teaser with the normals overlay. This is specifically what I would like to capture (not the OBJ sequence in .pkl). The resulting front-view output is the mesh overlay. Please be so kind as to indicate where in the code I can enable normals output.

Also, one more suggestion for you (if you will have desire + time): I find the OpenPose library to be very inaccurate for many complex movements. For example, the fencing sequence --- it breaks down half-way into the movement by flipping the character's direction:

![image](https://user-images.githubusercontent.com/47434136/175099686-087bc8c3-d347-421d-a929-c8f0ac7fa994.png)

If you will replace OpenPose with [HuMoR](https://github.com/davrempe/humor), this project would be in a league of its own. Please consider it. I would help, but I have very little time to spare.

**Comment by MoyGcc** [comment]
Hi, thank you very much for your efforts in debugging it, and sorry for the inconvenience! I will get back to this project for a more clean codebase once I have spare time to do so. But your remarks here would definitively be beneficial for other folks who want to run this project pipeline.

Regarding your question, you can simply modify the rendering mode here https://github.com/MoyGcc/hpcwild/blob/main/smpl_rendering/smpl_renderer.py#L173 according to your need and in your case you can just use the mode ``norm`` for rendering the normal map. 

Thank you again for your kind words and for indicating a better module for pose estimation. I will really try it once I have time to retake this project after a while. Any pr would be welcomed!
